Repository U-is-Ni-in-Korea/Android-United, pull requests merged in 2023-12, with the labels that each got.

#148 #145 / 닉네임 UX 변경 반영
  app/src/main/res/layout/activity_enter_invite_code.xml
  app/src/main/res/values/strings.xml
Labels: UI, 태희 :fox_face:

#149 #147 / 초대 코드 입력 뷰에서 입력 상태에 따른 처리 수정
  app/src/main/java/sopt/uni/presentation/common/content/ContentBindingAdaptor.kt
  app/src/main/res/layout/activity_enter_invite_code.xml
Labels: feat, 태희 :fox_face:

#153 #152 / 커플 해제시 파트너 ID 값 변경
  app/src/main/java/sopt/uni/presentation/mypage/MypageAccountDialogFragment.kt
Labels: Release, 준희 :raccoon:

#163 #160/소원권 Ui 수정
  app/src/main/java/sopt/uni/presentation/wish/WishActivity.kt
  app/src/main/java/sopt/uni/presentation/wish/fragment/WishUseMyFragment.kt
  app/src/main/res/layout/activity_wish.xml
  app/src/main/res/values/strings.xml
Labels: UI, 수빈 :unicorn:

#164 #162 / 타이머 수정
  app/src/main/java/sopt/uni/presentation/timer/TimerActiveFragment.kt
  app/src/main/java/sopt/uni/presentation/timer/TimerDialogFragment.kt
  app/src/main/res/layout/fragment_timer_active.xml
  app/src/main/res/layout/fragment_timer_setting.xml
  app/src/main/res/values/dimens.xml
Labels: fix, Pull Request :fire:, 준희 :raccoon:

#174 #173 / [QA] 무승부 라이팅 변경
  app/src/main/res/values/strings.xml
Labels: 준희 :raccoon:, QA

#181 #162 / [QA] 백 버튼 누를떄 다이얼로그 띄우기
  app/src/main/java/sopt/uni/presentation/timer/TimerStartActivity.kt
Labels: 준희 :raccoon:, QA
