Repository U-is-Ni-in-Korea/Android-United, pull requests merged in 2023-07, with the labels that each got.

#2 #1 / CI 세팅
  .github/workflows/pr_checker.yml
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/androidTest/java/sopt/uni_aos/ExampleInstrumentedTest.kt
  app/src/main/java/sopt/uni_aos/MainActivity.kt
  app/src/test/java/sopt/uni_aos/ExampleUnitTest.kt
Labels: chore, Pull Request :fire:, 태희 :fox_face:

#3 #1 / 프로젝트 기초 세팅
  .github/workflows/pr_checker.yml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_uni-playstore.png
  app/src/main/java/sopt/uni_aos/MainActivity.kt
  app/src/main/java/sopt/uni_aos/UniApplication.kt
  app/src/main/java/sopt/uni_aos/data/entity/ExampleEntity.kt
  app/src/main/java/sopt/uni_aos/data/repository/example/ExampleRepository.kt
  app/src/main/java/sopt/uni_aos/data/repository/example/ExampleRepositoryImpl.kt
  app/src/main/java/sopt/uni_aos/data/service/ExampleService.kt
  app/src/main/java/sopt/uni_aos/data/source/local/Example.kt
  app/src/main/java/sopt/uni_aos/data/source/remote/request/ExampleRequestDto.kt
  app/src/main/java/sopt/uni_aos/data/source/remote/response/ExampleResponseDto.kt
  app/src/main/java/sopt/uni_aos/di/RepositoryModule.kt
  app/src/main/java/sopt/uni_aos/di/RetrofitModule.kt
  app/src/main/java/sopt/uni_aos/di/ServiceModule.kt
  app/src/main/java/sopt/uni_aos/presentation/MainActivity.kt
  app/src/main/java/sopt/uni_aos/util/Event.kt
  app/src/main/java/sopt/uni_aos/util/EventObserver.kt
  app/src/main/java/sopt/uni_aos/util/binding/BindingActivity.kt
  app/src/main/java/sopt/uni_aos/util/binding/BindingAdapter.kt
  app/src/main/java/sopt/uni_aos/util/binding/BindingFragment.kt
  app/src/main/java/sopt/uni_aos/util/extension/ActivityExt.kt
  app/src/main/java/sopt/uni_aos/util/extension/ContextExt.kt
  app/src/main/java/sopt/uni_aos/util/extension/ItemDiffCallback.kt
  app/src/main/java/sopt/uni_aos/util/extension/ParcelableExt.kt
  app/src/main/java/sopt/uni_aos/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_uni_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_uni.xml
  app/src/main/res/mipmap-anydpi-v26/ic_uni_round.xml
  app/src/main/res/mipmap-hdpi/ic_uni.png
  app/src/main/res/mipmap-hdpi/ic_uni_foreground.png
  app/src/main/res/mipmap-hdpi/ic_uni_round.png
  app/src/main/res/mipmap-mdpi/ic_uni.png
  app/src/main/res/mipmap-mdpi/ic_uni_foreground.png
  app/src/main/res/mipmap-mdpi/ic_uni_round.png
  app/src/main/res/mipmap-xhdpi/ic_uni.png
  app/src/main/res/mipmap-xhdpi/ic_uni_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_uni_round.png
  app/src/main/res/mipmap-xxhdpi/ic_uni.png
  app/src/main/res/mipmap-xxhdpi/ic_uni_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_uni_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_uni.png
  app/src/main/res/mipmap-xxxhdpi/ic_uni_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_uni_round.png
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: chore, 태희 :fox_face:

#6 #1 / README파일 작업
  README.md
Labels: 수빈 :unicorn:

#9 #1 / README파일 Sparkle로 수정
  README.md
Labels: add, 수빈 :unicorn:

#73 # 65/ 닉네임 공백 로직 수정
  app/src/main/java/sopt/uni/presentation/invite/NickNameViewModel.kt
  app/src/main/java/sopt/uni/presentation/mypage/MypageProfilEditActivity.kt
Labels: feat, Pull Request :fire:, 준희 :raccoon:

#75 # 65/ EditText box 초기 색상, 깜빡이 오류 수정
  app/src/main/java/sopt/uni/presentation/invite/EnterInviteCodeActivity.kt
Labels: feat, Pull Request :fire:, 준희 :raccoon:

#76 # 65/ edittext 커서, 하이라이트 색상 수정
  app/src/main/res/values/themes.xml
Labels: feat, Pull Request :fire:, 준희 :raccoon:

#82 # 65/텍스트 폰트 수정
  app/src/main/res/layout/activity_mission_record.xml
  app/src/main/res/layout/item_mission.xml
Labels: UI, Pull Request :fire:, 준희 :raccoon:
